emilybache/GildedRose-Refactoring-Kata

- elixir/config/config.exs
- elixir/lib/gilded_rose.ex
- elixir/lib/item.ex
- elixir/mix.exs
- elixir/test/gilded_rose_test.exs
- elixir/test/test_helper.exs
Hi Emily,
Here's the Elixir version I recently wrote for the problem.
Look forward to your feedback.
Makis
> Add Elixir version

- GildedRoseRequirements_fr.txt
Added a file containing the translation of the requirements in French. The technical names are written in French and English to ease linking them to the code.
> Requirements translation in French

- GildedRoseRequirements_fr.md
- use Mardown
- spelling and grammar
> Fix french translation

- GildedRoseRequirements.txt
- README.md
Update URL for the "Writing Good Tests for the Gilded Rose Kata" post (the previous one links to an older version of Emily's blog).
> Update URL for a blogpost linked in the README

- swift/GildedRose.swift
- swift/GildedRoseTest.swift
- swift/Item.swift
- swift/main.swift
Hello,
Here is a Swift (v2) port I built using the Java and C# versions of the code.
> Add Swift port

- Groovy/.gitignore
- Groovy/.idea/compiler.xml
- Groovy/.idea/copyright/profiles_settings.xml
- Groovy/.idea/misc.xml
- Groovy/.idea/modules.xml
- Groovy/Groovy.iml
- Groovy/readme.txt
- Groovy/src/com/gildedrose/GildedRose.groovy
- Groovy/src/com/gildedrose/GildedRoseTest.groovy
- Groovy/src/com/gildedrose/Item.groovy
- Groovy/src/com/gildedrose/TexttestFixture.groovy
I have taken the Java version and ported it to Groovy. 
Removed the semicolons at the end of the lines and the public markers from fields. Added "as Item[]" where necessary. Used def instead of explicit types in some places.
Added some instructions how to run the tests from IntelliJ, Eclipse and on the command line.
> Gilded Rose for Groovy

- clisp/gilded-rose.lisp
My esteemed colleague and sempai Rainer Joswig (@lispm on Github) has created a version of the Kata in Common Lisp.
> Common Lisp version by Rainer Joswig

- Kotlin/.gitignore
- Kotlin/Kotlin.iml
- Kotlin/src/com/gildedrose/GildedRose.kt
- Kotlin/src/com/gildedrose/GildedRoseTest.kt
- Kotlin/src/com/gildedrose/Item.kt
- Kotlin/src/com/gildedrose/TexttestFixture.kt
Largely a copy of the Java-version of the Gilded Rose Kata,
> Added Kotlin version of the Gilded Rose Kata

- swift/main.swift
- Fixed copy/paste errors in items
- Removed unnecessary comment blocks
Fixes #45
> Fixed copy/paste errors in test data

- GildedRoseRequirements_es.md
I'd like to contribute with the spanish translation
> Adds the spanish translation

- js/spec/gilded_rose_spec.js
- js/src/gilded_rose.js
Uses the new `class` keyword.
Adds the `Shop` entity, with an `updateQuality` message.
> Updates examples using ES2015 class syntax

- scala/.gitignore
- scala/build.sbt
- scala/project/.gitignore
- scala/project/build.properties
Versions upgraded to :
Scala - 2.12.1 
Sbt  - 0.13.13
Scalatest - 3.0.1
> upgraded Scala version to latest versions

- TypeScript/.gitignore
- TypeScript/app/gilded-rose.ts
- TypeScript/package.json
- TypeScript/test/guilded-rose.spec.ts
- TypeScript/test/mocha.opts
- TypeScript/tsconfig.json
I ported the JS version to TypeScript.
The project uses mocha for unit testing and reports code coverage.
> Added GildedRose for TypeScript

- TypeScript/test/guilded-rose.spec.ts
- js/spec/gilded_rose_spec.js
- 'gilged' to 'gilded' in respective specs
> fix(js and ts): spec typo

- js/TexttestFixture.html
- js/src/gilded_rose.js
- broken after last commit which updated gilded_rose.js to use ES2015 class syntax
- creates instance of class Shop
- creates items array
- updates showItemsFor
> Fix TexttestFixture

- go/gilded-rose.go
> Fix spelling in Go files

- pascal/.gitignore
- pascal/README.md
- pascal/ROSE.PAS
- pascal/ROSE_T.PAS
- pascal/TEXTTEST.PAS
- pascal/TPUNIT.PAS
> Port to (Turbo) Pascal. Feeling retro ;-)

- scala/project/build.properties
- scala/src/test/scala/com/gildedrose/TexttestFixture.scala
Hi
This PR adds TexttestFixture.scala. It runs exactly like java version of this file.
By the way, sbt is upgraded to latest stable version. The old version crashed with message unable to parse int "0x100"
Cheers,
Anh-Vu
> add TexttestFixture.scala

- GildedRoseRequirements_fr.md
It's better with this modification.
du rage -> une rage
French is my mother tongue.
> Improve french sentence

- COBOL/mf/src/.cobolProj
- COBOL/mf/src/.gitignore
- COBOL/mf/src/.project
- COBOL/mf/src/GildedRose.cbl
Could you take a quick look to see that i haven't done any big mistakes.
Ill add testcase similar to the one in Python, before this pr should be merged.
> Translate Python example to Micro Focus COBOL.

- COBOL/mf/src/.cobolProj
- COBOL/mf/test/.cobolProj
- COBOL/mf/test/.gitignore
- COBOL/mf/test/.project
- COBOL/mf/test/TestGildedRose.cbl
I have now added a test project so that you dont need to start from scratch when writing tests for Gilded Rose in COBOL.
> Cobol test project

- xslt/.gitignore
- xslt/README.md
- xslt/build.xml
- xslt/gilded_rose.dtd
- xslt/texttest_fixture.xml
- xslt/tst_update_quality.xsl
- xslt/update_quality.xsl
- xslt/xsltunit-0.2/xsltunit.xsl
- xslt/xsltunit-0.2/xsltunit_report.xsl
I managed to port it to XSLT almost keeping the original cascading IFs together with a sample test using xsltunit.
> Port to XSLT

- plpgsql/README.md
- plpgsql/code/update_quality.sql
- plpgsql/structure/create.sql
- plpgsql/test/data/load.sql
- sql/README.md
- sql/code/update_quality.sql
- sql/structure/postgreSQL/create.sql
- sql/test/data/load.sql
PL/pg SQL is the procedural language for PostgreSQL DB, like PL/SQL for Oracle DB.
This proposal is bare metal, without  any test framework, but it works !
> Add PL/pg SQL (without test support)

- scala/build.sbt
- scala/project/build.properties
- scala/src/test/scala/com/gildedrose/GildedRoseTest.scala
- scala/src/test/scala/com/gildedrose/TexttestFixture.scala
Sbt: 1.3.9
Scala: 2.13.1
scalaTest: 3.1.1
> Update Scala versions

- js-jasmine/spec/texttest_fixture.js
- js-jest/test/texttest_fixture.js
- js-mocha/test/texttest_fixture.js
Adds a javascript version of ruby/texttest_fixture.rb to be used when choosing js-jest, js-mocha or js-jasmine projects.
> Add a text test fixture for javascript projects

- texttests/config.gr
This assumes that the user would compile the TS files themselves or setup some automatic workflow.
> Create texttest settings for TypeScript version

- TypeScript/.mocharc.js
- TypeScript/package.json
- TypeScript/test/mocha.opts
This PR only solves the problem, it doesn't make it pretty. 
There is a lot of things in the package.json that probably should be replaced with other projects or should be configured more standardly but at least the code can now be run!
> Update typescript dependencies and the mocharc file

- python/test_gilded_rose.py
Add blank lines to test_gilded_rose.py
> Add blank lines

- fortran/CMakeLists.txt
- fortran/README.md
- fortran/src/GildedRose.f90
- fortran/test/GildedRose_text_test.f90
- fortran/test/GildedRose_unity_test.f90
First commit of Fortran version of GildedRose
I followed the C version the best I could but I could not make the C-version build so I compared the output to the python version and it looked OK.
I hope to use this code kata some day at my company where we still happily use Fortran for numerical stuff aka HPC. Fortran is not the coolest language but still used and for numerics it is still hard to beat. :-)
> First commit of Fortran version of GildedRose

- Java-Spock/build.gradle
- Java-Spock/gradle/wrapper/gradle-wrapper.properties
Just found that the gradle was bit lower version, which was not compatible with latest Intellij (CE) version. So, bumped the gradle version. Then, realized spock is also a bit old. So, updated that too.
> Upgraded gradle and spock

- swift/Sources/GildedRose/GildedRose.swift
- swift/Sources/GildedRose/Item.swift
- swift/Sources/GildedRoseApp/main.swift
Applied AppCode inspections to do automatic clean-up
> Make Swift more idiomatic

- csharpcore/GildedRose/GildedRose.csproj
- csharpcore/GildedRoseTests/GildedRoseTests.csproj
Description of changes: 
- Update packages
- Update framework version from .net core 3.1 to .net 6.0 
If it is beneficial, I can also refactor the code to use file scoped namespace as introduced in C#10. I wanted to keep this low impact for now and iterate on any addition changes as necessary.
> Update packages and framework for csharpcore

- GildedRoseRequirements_de.md
- README.md
Years ago I asked myself why there is no german translation of the requiremts. Now I have found the time to try my hand at it.
> German translation of requirements

- TypeScript/README.md
- TypeScript/test/golden-master-text-test.ts
Hi there,
I've changed run script import to fix an error with app import, I've also added code to take number of days to simulate from args. New section about how to run the app added to README.
> Fix and document Typescript app run

- GildedRoseRequirements_de.md
adding missing commas, fixing a few typos, use more natural expression
> improve language

- GildedRoseRequirements_pl.md
this PR adds polish translation for Gilded Rose requirements
> add polish translation of requirements

- swift/Package.swift
- swift/Sources/GildedRose/GildedRose.swift
- swift/Sources/GildedRose/Item.swift
- swift/Sources/GildedRoseApp/main.swift
- swift/Tests/GildedRoseTests/GildedRoseTests.swift
> Apply SwiftFormat

- php/composer.json
- php/composer.lock
There are no more tags or branches in this dependency, just `Main`.
> **Note**: You can confirm this here: https://packagist.org/packages/approvals/approval-tests
This is the composer.lock diff after updating `approvals/approval-tests` to use `Main` branch:
```
php/ (php/update-approvals-dependency) $ ~/.composer/vendor/bin/composer-lock-diff --from=/tmp/composer-dev.lock --to=composer.lock    [10:03:30]
+---------------------------------------+-----------+---------+-------------------------------------------------------------------------------+
| Dev Changes                           | From      | To      | Compare                                                                       |
+---------------------------------------+-----------+---------+----------------------------------------- …
```
> Bugfix: Update approvals php dependency

- GildedRoseRequirements_fr.md
> removed a word that didn't mean anything in the sentence in french

- TypeScript/jest.config.ts
- TypeScript/package-lock.json
- TypeScript/package.json
- TypeScript/test/vitest/gilded-rose.spec.ts
- TypeScript/tsconfig.json
- TypeScript/vitest.config.ts
I've also updated and adapted dependencies.
> Add vitest inside TypeScript

- Kotlin/build.gradle.kts
- Kotlin/src/main/kotlin/com/gildedrose/GildedRose.kt
- Kotlin/src/test/kotlin/com/gildedrose/GildedRoseTest.kt
- Kotlin/src/test/kotlin/com/gildedrose/TexttestFixture.kt
A couple of tweaks to make things up to date
> Update versions in Kotlin variant, and use List rather than Array

- GildedRoseRequirements_it.md
- README.md
- [x ] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.
Improve GildeRoseRequirements Italian translation
Add Italian translation link to README.md
> Update Italian translation:

- texttests/config.gr
TextTests configuration was missing for PHP. Since I made it for myself, better share it
> TextTests configuration for PHP

- js-jest/package-lock.json
updated package-lock.json to remove vulnerabilities
> updated package-lock.json to remove vulnerabilities

- csharp/App.config
- csharp/csharp.csproj
- csharp/packages.config
This pull request brings the C# starting point forward to a version that may target more modern development environments. The previous .NET version (before this pull request) was 4.5.2, which went out of support in April 2022.
This pull request also updates a few essential NuGet packages, most notable _NUnit_ and _ApprovalTests_.
---
Why not upgrade to .NET Core?
Only because I wanted to ask before sending such a pull request. This (.NET 4.8.1) I consider a bare minimum to ask anyone to do the exercise today.
> Upgrade C# to .NET 4.8.1

- js-jest/package-lock.json
- js-jest/package.json
- [ X] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.
Update Jest dependency for a better testing experience, especially on windows machines
> update jest for better testing experience

- ocaml/dune-project
- ocaml/gilded_rose.opam
- ocaml/lib/dune
- ocaml/lib/gilded_rose.ml
- texttests/config.gr
Following the recommendations in #488, this PR updates the OCaml directory and the `config.gr` file to support the `testtext` test suite using the main program.
> Support texttest with OCaml

- csharpcore/GildedRose/GildedRose.csproj
- csharpcore/GildedRoseTests/ApprovalTest.cs
- csharpcore/GildedRoseTests/GildedRoseTest.cs
- csharpcore/GildedRoseTests/GildedRoseTests.csproj
- csharpcore/GildedRoseTests/TextTestFixture.cs
- [ X] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.
This PR makes csharpcore work. 
I add a missing NuGet, use only one test framework, downgrade to stick to NET6 LTS and var some variable declarations.
Tested on Visual Studio Mac and Visual Studio 2022 for Windows.
this resolves #465
> make csharpcore work. 

- GildedRoseRequirements_eu.md
- README.md
I prepared requirements translation in Basque (Euskara) and I would be very happy if you add them to the main repository.
> Add Basque (Euskara) requirements translation

- nim/src/gildedrose.nim
- nim/src/items.nim
- nim/test/gilded.nim
It may be interesting to see how this is refactored in Nim. Particularly I'd be interested to see if anyone gets it to the point of being able to write a macro.
It doesn't have support for texttest, but it uses Nim's unittest module and picks a few critical test cases, so it should be fairly usable by just running that module.
Also Nim's object model prefering value semantics over reference semantics required a small top level API change where rather than a command pattern class, I just have a function.
> Gilded rose in Nim

- jq/README.md
- jq/gilded-rose.jq
- jq/test-gilded-rose.sh
- jq/texttest_fixture.jq
1. Use jq instead of jaq (which is more common)
2. Don't use `foreach` - unnecessary
3. simplify `... else . end` -> `... end`
4. texttest fixture: fix off-by-one in looping through `days`
> jq: simplify

- ruby/README.md
I noticed this lil issue when having a go at the Ruby kata today :)
> doc - update command to run ruby tests

- php/tests/ApprovalTest.php
Hello,
This PR fixes the code formatting in one of the PHP tests. The other files are fine.
> Fix ApprovalTest code formatting

- GildedRoseRequirements_nl.md
- [ ✓ ] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.
This PR adds a Dutch translation to the requirements markdown
> Added Dutch requirement specification Markdown translation

- texttests/config.gr
- zig/.gitignore
- zig/README.md
- zig/build.zig
- zig/src/gilded_rose.zig
- zig/src/main.zig
A [Zig](https://ziglang.org/) implementation of the kata.
I'm still a noob in Zig, this is my first ever project, but I think it runs correctly.
TestTexts are implemented and seem to work.
I'll probably continue to play with it so I might push some improvements later.
PS: thanks for maintaining this project, you're awesome :pray:
> Add Zig implementation

- haskell/.gitignore
> add working directories to haskel .gitignore

- elm/elm.json
- elm/src/Main.elm
Remove one unused file.
Update dependencies, remove unused dependencies.
This is mostly a generic cleanup, I have another PR ready that actually does something to the code.
> Update dependencies for Elm

- elixir/config/config.exs
- elixir/lib/texttest_fixture.ex
Added `texttest_fixture` for Elixir
> Added text test fixture for Elixir

- gleam/gleam.toml
- gleam/src/program.gleam
> refactor: update gleam_stdlib and glint version

- io/.gitignore
- io/README.md
- io/io/GildedRose.io
- io/io/Item.io
- io/package.json
- io/tests/correctness/GildedRoseTest.io
- io/tests/correctness/TexttestFixture.io
- io/tests/correctness/run.io
> Port to Io language.

- TypeScript/test/vitest/approvals.spec.ts
This is a port of TypeScript approval tests from Jest to Vitest.
> Port TypeScript approval tests from Jest to Vitest

- Kotlin/build.gradle.kts
- Kotlin/gradle/wrapper/gradle-wrapper.properties
Upgrading versions for the Kotlin project
> Upgrading versions for the Kotlin project

- elixir/lib/texttest_fixture.ex
- elixir/test/ApprovalTest.ThirtyDays.verified.txt
- elixir/test/gilded_rose_test.exs
Added an approval test for the elixir programming language and fixed the printing in the text test fixture
> Elixir approval test

- lua/.gitignore
- lua/README.md
- lua/gildedrose-dev-1.rockspec
- lua/spec/gilded_rose_spec.lua
- lua/src/gilded_rose.lua
- lua/src/item.lua
- lua/src/main.lua
- lua/texttest
- texttests/config.gr
An implementation of the Kata in Lua
I'm still learning it so probably everything is not perfect (had to hack a little to make the TextTest suite work)
I will revisit if I learn how to make things better
Also I used the Busted test suite, so maybe we'll have to move to ./lua-busted if someone wants to add other tools later on ?
> add Lua lang
