cpp/CMakeLists.txt
I added CMake support for C++. It can be ignored in favor of the existing Makefile.
The CMake FindThreads bug is [#15058](http://www.cmake.org/Bug/view.php?id=15058).
=> CMake support.

README.md
Cyber-dojo links in README.md currently point to the .com domain, which is no longer valid. This pull request changes all links to .org, which is the active cyber-dojo web site.
I then confirmed that almost all of the modified links worked in the manner expected. However, the [C# link](http://cyber-dojo.org/forker/fork/107907AD1E?avatar=alligator&tag=13) in README.md does not appear to create a working fork; it simple goes to the cyber-dojo home page.
This change helped several people in a code retreat workshop today; hope it's useful for others too.
=> Update cyberdojo links to .org

swift/main.swift
Process enum has been replaced with CommandLine in Swift 3. Changed main.swift to reflect this.
Fixes #43
=> Updated for Swift 3

elixir/lib/gilded_rose.ex
Why:
- The current version isn't implemented properly.
Additional information:
- This is the result of my local test run (test omitted since
they're a part of the kata):
GildedRoseTest
* test update_quality/1 Aged Brie actually increases in Quality
the older it gets
* test Backstage passes Quality increases by 2 when there are
10 days or less
* test update_quality/1 the quality of an item is never negative
* test update_quality/1 degrades the quality when a day passes
* test Backstage passes Quality increases by 3 when there are 5
days or less
* test update_quality/1 when sell date is passed it degrades twice
as fast
* test Backstage passes Quality increases by 1 when sell_in is
larger than 10
* test update_quality/1 does not change the name
* test update_quality/1 The Quality of an item …
=> Proposed fix for #34: Implement a working version of the original code for the kata

README.md
Following cyber-dojo.org java katas are broken, Probably because of an upgrade of the cyber-dojo server and its components:
* JUnit, Java
* C#
* Cucumber, Java
I fixed these cyber-dojos and updated the links in the README.md to use the new versions.
=> Fix cyber dojos

.gitignore
Included to the gitignore also the elixir __build_ folder path, as well already done for the perl6 _.precomp_ folder.
=> Added elixir build folder to ignored files

csharp/csharp.csproj, csharp/packages.config
The NUnit-Test-Adapter is needed as either Visual Studio extension or NuGet package so test runners can discover the NUnit tests. I prefer the NuGet package since then it works on every machine that has just checked out the code without installing any additional extensions.
BR
=> Added NUnit Test Adapter for discovering test in VS

cpp/Makefile
I don't know Google Test at all well, but it seems the API has changed. Without this change, I get errors linking `GildedRose`:
```
Undefined symbols for architecture x86_64:
"testing::InitGoogleTest(int*, char**)", referenced from:
_main in gtest_main.a(gtest_main.cc.o)
[...many more...]
```
With this change, `make` succeeds, and `./run_once.sh` gives me a red "fixme" test.
=> With Google Test 1.8.0, I seem to need both libs.

cpp/CMakeLists.txt, cpp/GildedRoseApprovalMain.cc, cpp/GildedRoseApprovalTests.VerifyCombinations.approved.txt, cpp/GildedRoseApprovalTests.cc, cpp/run-approval-once.sh, cpp/run-once-cmake.sh
* Add testcase using https://github.com/approvals/ApprovalTests.cpp and google test.
* Change google test to be downloaded if not installed with cmake
* Add a run-once-cmake.sh script to build and test with cmake
* Add a run-approval-once.sh script to build and run approval test
=> Add ApprovalTests for cpp

haskell/README.md, haskell/gilded-rose.cabal, haskell/install_deps.sh, haskell/run.sh, haskell/stack.yaml, haskell/test.sh
Hello,
This small pull request updates the haskell base version required by `cabal`, as it seems to be a bit outdated. It also provides a `stack.yml` file and suggests to install `stack` so that shell scripts are not needed anymore (and have been removed to avoid redundancy).
At last, it looks like https://github.com/sheyll/gilded-rose-haskell has not been updated for about 4 years. So, the text that mentions it in the README has also been removed.
=> chore(haskell): update base and add stack file

TypeScript/app/gilded-rose.ts
Without a type annotation, TS expects the argument in the ctor to be a never[], hence "npm test" fails to even start
=> Fix compile error in TS

js-jest/.gitignore, js-jest/README.md, js-jest/package-lock.json, js-jest/package.json, js-jest/src/gilded_rose.js, js-jest/test/gilded_rose.test.js
- Added Jest test framework
- Included the following `npm` scripts:
- `npm test` - to run all tests once
- `npm run test:watch` - to run all tests and watch for changes
- `npm run test:coverage` - to run tests and generate a coverage report
=> Add Gilded Rose kata for JavaScript with Jest

Java/pom.xml, Java/src/test/java/com/gildedrose/GildedRoseTest.java
As JUnit 5 is the new major version for over 2 years now, I thought it would be time to get rid of legacy versions ;-)
=> migrate to JUnit 5

cpp/README.md, cpp/test/cpp_catch2_approvaltest/CMakeLists.txt, cpp/test/cpp_catch2_unittest/CMakeLists.txt, cpp/test/cpp_googletest_approvaltest/CMakeLists.txt, cpp/test/cpp_googletest_unittest/CMakeLists.txt
This is a minor change to the excellent #133 - to allow support for C++11 and C++14...
It updates both the CMake files and the readme.
=> Reduce required C++ level from 17 to 11 - no code changes needed.

php7/src/GildedRose.php
For some reason the php7 version sets the quality of sulfuras to be 80.
The sepcification simply states this is the max, and that it does not change, as 
written on line 22 of the english specifications.:
https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/master/GildedRoseRequirements.txt#L22
=> Remove quality change on sulfuras

README.md
Like the the README.md files for Racing-Car-Katas and the Tennis-Refactoring-Kata did, this README.md for GildedRose-Refactoring-Kata has. 
**(This is my last PR about cyber-dojo. I noticed this issue on the two repos I used recently. I won't be going on a hunt through other repos.)**
=> Remove broken links to cyber-dojo from README.md

rust/src/main.rs
The main method for approval tests are supposed to run 30 days.
Previous impl was using an exclusive range.
Use an inclusive range instead.
=> Make rust text based approval tests pass

texttests/environment.gr
The suggested texttest environment config Java (classpath), doesn't work with the default maven/gradle build directories.
This change should fix the issue.
Co-Authored-By: Kristóf Juhász <76943150+kristof-juhasz@users.noreply.github.com>
Co-Authored-By: mariettas <47053959+mariettas@users.noreply.github.com>
Co-Authored-By: Marc Monserrat Núñez <32415447+munsa@users.noreply.github.com>
Co-Authored-By: Mauro Ceraso <76943029+mauroceraso@users.noreply.github.com>
Co-Authored-By: Norbert Toth <75730727+norbertgabortoth@users.noreply.github.com>
=> Fix texttest Java classpath for maven and gradle builds

dart/pubspec.yaml
As of Dart 2.12, omitting the SDK constraint is an error. When the pubspec has no SDK constraint, pub get fails with a message like the following:
```yaml
environment:
sdk: '>=2.10.0 <3.0.0'
```
This PR fix that issue and update test dependcy to support the latest dart version. More [here](https://dart.dev/tools/pub/pubspec#sdk-constraints)
=> Dart : Fix sdk constraint and update test deps

js-jasmine/package.json, js-mocha/package.json
Update to Babel 7 to avoid stern warnings during `npm install`
Update Mocha to version 8, also to avoid warnings and be compatible with
Babel 7
=> Update dependencies for JavaScript

Java/.editorconfig
[Editorconfig](https://editorconfig.org/) is a great way to make configuration consistent across various IDEs, and works [out-of-the-box](https://editorconfig.org/#pre-installed) with the most popular editors, IntelliJ IDEA included.
Rationale of the PR: my user-level preferences is an indentation size of 2, but the Java project uses a width of 4. So when I reformat the whole document, every lines are changed; and that’s not what we want.
Maybe the file `Java/.editorconfig` could be brought at the project root, but I’m not an expert in other languages.
=> Add editorconfig file for Java

cpp-catch2/CMakeLists.txt
mingw32 compiler on windows gave me following error. This PR should fix it for cpp-catch2
Build error
```
Consolidate compiler generated dependencies of target gildedrose_catch2
[ 25%] Building CXX object CMakeFiles/gildedrose_catch2.dir/test/main.cpp.obj
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\gildedrose_catch2.dir\test\main.cpp.obj: too many sections (34736)
C:\Users\xr3\AppData\Local\Temp\ccmD84Ej.s: Assembler messages:
C:\Users\xr3\AppData\Local\Temp\ccmD84Ej.s: Fatal error: can't write 180 bytes to section .text of CMakeFiles\gildedrose_catch2.dir\test\main.cpp.obj: 'file too big'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10 …
```
=> Adding fix for mingw32 compiling on windows

csharpcore/csharpcore.csproj
I upgraded the csharpcore project from .NET Core 2.1 to the new LTS version: .NET Core 3.1. This is because the current version loses support on the 21st August 2021, and running the latest LTS is good practice. For more information, see [the .NET product lifecycle on Microsoft's website](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core).
I updated the csharpcore project's dependencies. This reduces the risk of people running into bugs or reading the wrong docs when completing this exercise. I ran the program and the tests after each package was upgraded to ensure that no compiler
warnings or changes in behavior were introduced.
=> Update csharpcore's .NET version and dependencies

swift/Package.swift, swift/README.md, swift/Sources/GildedRose/GildedRose.swift, swift/Tests/GildedRoseTests/GildedRoseTests.swift
The new version of `swift-tools-version` makes things easier… especially for adding new dependencies like the Swift version of ApprovalTests.
And while formatting is not universal, these spaces are much, much more common. Otherwise my eyes cross.
Updated test code to latest style. In particular, defining the test as `throws` makes it easier to use ApprovalTests.
=> Update Swift Package Manager, clean up starting test, add README

elixir/test/gilded_rose_test.exs
I noticed there was a placeholder for an Elixir unit test, but with no assertion, so it passed by default. I wrote a failing test to match the implementations in other languages.
=> Add initial failing test for Elixir

Java/pom.xml
Fixes the following warnings:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.gildedrose:gilded-rose-kata:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 29, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
and
```
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
```
=> Fix Maven warnings

swift/.gitignore, swift/Package.swift, swift/Tests/GildedRoseTests/GildedRoseTests.swift, swift/Tests/GildedRoseTests/XCTestManifests.swift, swift/Tests/LinuxMain.swift
- Ignore the generated Xcode project from the repositiory
- Bump the swift tools version to 5.5 (supported by Xcode 13+)
- Tidy the Tests. LinuxMain, XCTestManifests and the allTests array are no longer needed as tests are auto-discovered on non-apple platforms
=> Update the Swift starting point

Java/pom.xml, Java/src/main/java/com/gildedrose/Program.java, Java/src/test/java/com/gildedrose/ApprovalTest.java
The csharp directory contains approvaltests which enables a quick introduction to the processing of the kata. The java directory, however, lacks approvaltests.
This PR contains the java porting of the csharp main program as well as the approvaltest, in content 1:1 according to the csharp variant as well as the necessary entry in the pom.xml so that the starting position is the same for both java and csharp.
=> approval tests for java analog to csharp variant

cpp/test/cpp_texttest/GildedRoseTextTests.cc
The cpp kata doesn't compile due to syntax errors. This PR fixes those errors.
=> Fix syntax errors in cpp kata

php/phpstan.neon
You can use max as an alias for the max level, which is the 9
> **Note**: See: https://github.com/phpstan/phpstan-src/blob/1.9.x/conf/config.levelmax.neon
=> Update level: max in phpstan.neon

julia/.gitignore, julia/gilded_rose.jl, julia/runtests.jl
I based this implementation mostly on the Python implementation.
The one major difference I want to make explicit comes from the fact that Julia doesn't really want you to run scripts from the command-line. Instead, julia wants you to run functions from the REPL. Regardless, I left instructions in a comment on how to run `main()` from the command-line if someone wants to use that workflow. 
```bash
$ julia -e 'include("gilded_rose.jl"); main(;days=2)'
```
If you'd prefer, I could refactor and break one of julia's "rules" to create a true script that'd run more comparably to how the python implementation runs from the command-line.
```bash
$ julia texttest_fixture.jl
```
Let me know!
Thanks for all the great work maintaining this!
=> Add Julia Implementation

julia/gilded_rose.jl
Realised I should have made the Item struct use ints instead of reals, so just a fix for that.
=> Fix Item parametric type

rust/src/gildedrose.rs
The previous rust code uses a for loop that already loops over the items to update directly.
This makes the code worse and closer to the original by looping over indices instead and getting the item by index every time.
=> Make rust loop worse to make it closer to the original

julia/gilded_rose.jl, julia/texttest_fixture.jl, texttests/config.gr
This makes the output of the Julia main function match what's expected by texttest, and adds (commented out) configuration for Julia to config.gr.
=> Make Julia compatible with texttests

README.md
Some links still refer to the renamed branch `master` and requires redirection to `main`
Update them to point directly to `main`. While at it, update link to file to use `blob` instead of `tree` for a similar reason
Validation: clicked all 3 changed links to make sure they direct to the right place
=> Update README.md for master->main rename

csharp/ApprovalTest.cs, csharpcore-Verify.xunit/GildedRoseTests/ApprovalTest.cs, csharpcore/GildedRoseTests/ApprovalTest.cs
Pull request attending to a possible regression in the behavior of the Approval tests in DotNet 
introduced after 
https://github.com/emilybache/GildedRose-Refactoring-Kata/commit/e188faef86dd212cda5e4331d06e36f0ba76d2ef#diff-5e77a617e97d9e66a013c079bfbdb3eb0987e563b1a92aa74c2d0349bc88bb59
The Main program, used by the approval tests has a default number of Days set to 2 to support the texttests command line approval test - which is being updated to be a ubiquitous approval test adapter for any language
The tests in the DotNet targeted solutions are named ThirtyDays. 
Since they do not provide an override for the number of days, they are currently only running the business logic for 2 days.
(I believe that this means that the approval tests do not demonstrate the rule that the back stage …
=> Tests named 30 days are run over 30 days

README.md
=> Fix link to requirements

bash/texttest_fixture.sh
bash texttest fixture: use a variable instead of a temp file to hold the items state.
=> bash: simplify texttest fixture

csharpcore-Verify.xunit/GildedRose/GildedRose.csproj, csharpcore-Verify.xunit/GildedRoseTests/ApprovalTest.cs, csharpcore-Verify.xunit/GildedRoseTests/GildedRoseTests.csproj, csharpcore/GildedRose/GildedRose.csproj, csharpcore/GildedRoseTests/ApprovalTest.cs, csharpcore/GildedRoseTests/GildedRoseTest.cs, csharpcore/GildedRoseTests/GildedRoseTests.csproj
List of changes and reasoning:
- Update the .NET Core solutions to the latest major version 8
- Update all packages to their latest versions and accommodate for any breaking changes
- NUnit legacy assertions are replaced by the new assertions API, see https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html.
- `[UsesVerify]` attribute deprecated in the latest Verify lib versions
- In the NUnit version, replace https://github.com/approvals/ApprovalTests.Net for https://github.com/VerifyTests/Verify as recommended by the lib maintainers. This is the same library used in the Xunit version.
=> [Refactor] .NET Core Templates - Update Framework and Libraries

python/test_gilded_rose.py
should be `assertEqual`, as the other form has been deprecated since 2010 and since been removed
Original issue that triggered `assertEquals` being deprecated: https://bugs.python.org/issue9424
=> fix deprecated usage of assertEquals

csharpcore/README.md, texttests/config.gr
`csharpcore` was previously ported from .Net 7.0 to .Net 8.0. This PR only fixes a couple of references to the old .Net version (and directory) in the docs and `texttests/config.gr`.
=> fix small leftovers for csharpcore porting to .Net 8.0

swift/Package.swift
Fixes warning due to changes in Swift. The warning says:
'GildedRoseApp' was identified as an executable target given the presence of a 'main.swift' file. Starting with tools version 5.4.0 executable targets should be declared as 'executableTarget()'
=> swift: fix warning about executableTarget

swift/Sources/GildedRose/GildedRose.swift
`&&` is familiar to more people than Swift's comma operator. I'd like to change it back.
Benefits:
- Easier for folks newer to Swift
- Better automated mutation from Muter tool
=> swift: use && instead of , for beginners and for automated mutation

php/tests/ApprovalTest.php
Hello again,
I've just realized that one of the method calls in the ApprovalTest file is deprecated. This PR fixes this deprecation.
=> Update ApprovalTest fix the deprecated method call

csharp.NUnit/GildedRose.sln, csharp.NUnit/GildedRose/GildedRose.cs, csharp.NUnit/GildedRose/GildedRose.csproj, csharp.NUnit/GildedRose/Program.cs, csharp.NUnit/GildedRoseTests/ApprovalTest.cs, csharp.NUnit/GildedRoseTests/GildedRoseTests.csproj, csharp.NUnit/global.json, csharp.xUnit/GildedRose.sln, csharp.xUnit/GildedRose/GildedRose.cs, csharp.xUnit/GildedRose/GildedRose.csproj, csharp.xUnit/GildedRose/Item.cs, csharp.xUnit/GildedRose/Program.cs, csharp.xUnit/GildedRoseTests/ApprovalTest.cs, csharp.xUnit/GildedRoseTests/GildedRoseTest.cs, csharp.xUnit/README.md, csharp.xUnit/global.json
- Use file-scoped namespaces everywhere
- Changed csproj files : added RootNamespace
- Removed `NUnit/GildedRoseTests/TextTestFixture.cs` because the same logic is defined in `csharp.NUnit/GildedRose/Program.cs`
- Program.cs is the same for both (⭐: actually I think it's even better to only have 1 main GildedRose project which is defined in the NUnit project and referenced in the other xUnit project)
- small changes from `GildedRose(IList<Item> Items)` to `GildedRose(IList<Item> items)` and `IList<Item> Items;` to `private readonly IList<Item> _items;` to be more conformant with C# .NET coding guidelines.
=> Refactoring c# projects

.github/pull_request_template.md, CONTRIBUTING.md, README.md
Discussed here: https://github.com/emilybache/GildedRose-Refactoring-Kata/pull/548#issuecomment-2156754222
I remembered you already had some of this in `README.md` and therefore I extended it with a recommended project structure. It is obviously tricky because the language conventions can vary greatly (e.g. Java versus gleam). 
I also added a TODO in the PR template to ensure contributors read the section on adding a new language.
If you would rather move this whole section to `CONTRIBUTING.md` I am happy to do so 😄
=> Add a CONTRIBUTING.md to clarify project structure and valid contributions

Java-Approvals/gradle/wrapper/gradle-wrapper.properties, Java-Cucumber/gradle/wrapper/gradle-wrapper.properties, Java-Spock/gradle/wrapper/gradle-wrapper.properties, Java/gradle/wrapper/gradle-wrapper.properties
I noticed that the Gradle Java projects are not compatible when with newer Java versions. This can be solved by upgradle to a newer version.
=> Make Gradle Java projects compatible with Java 17+

Kotlin/build.gradle.kts
If you clone the repo, navigate to the Kotlin directory and run `./gradlew -q text`, it fails because gradle doesn't have a `text` task. This PR adds this task. 
I translated the task found in the Java build.gradle to maintain the behaviour, and now `./gradlew -q text` works!
=> Enable texttest to run in the Kotlin project

ruby/texttest_fixture.rb
It looks like the Ruby example was based on the Python one, but this is not the correct syntax for keywords arguments in Ruby. It doesn't cause an error, but it also doesn't provide any benefit, since the argument names aren't validated.
If keyword arguments were used, it would look like:
`Item.new(name: "Aged Brie", sell_in: 2, quality: 0),`
and the initializer would need to be updated.
=> Fix incorrect Ruby syntax
